---
- name: install gcc & python devel  package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
    - gcc
    - python-devel
    - python-pip

- name: install docker packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_packages }}"

- name: Upgrade pip
  pip:
    name: pip
    extra_args: --upgrade

- name: Install / Upgrade setuptools
  pip:
    name: setuptools
    extra_args: --upgrade

- name: install pip package for molecule
  pip:
    name: "{{ item }}"
  with_items: "{{ pip_packages }}"
